#include "jmesh_app_svc.h"

#define JMESH_PROV_SVC_UUID {0x03,0xff}

svc_env_t jmesh_prov_svc_env;

struct gattm_svc_desc const jmesh_prov_svc_desc ={
        .start_hdl = 0,
        .task_id = TASK_ID_AHI,
        .perm = 0,
        .nb_att = JMESHS_IDX_PROV_NB,
        .uuid = JMESH_PROV_SVC_UUID,
};
struct gattm_att_desc const jmesh_prov_svc_att_db[JMESHS_IDX_PROV_NB] = {


    [JMESHS_IDX_MESH_PROVISIONING_DATA_IN_CHAR]     = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_PROVISIONING_DATA_IN_VAL]      = {{0xfe,0x2a},PERM(WP, NO_AUTH)|PERM(WRITE_REQ, ENABLE), PROVISION_DATA_MAX_LENGTH, PERM(RI, ENABLE)},
    
    [JMESHS_IDX_MESH_PROVISIONING_DATA_OUT_CHAR]    = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_PROVISIONING_DATA_OUT_VAL]     = {{0xff,0x2a}, PERM(RD, ENABLE)|PERM(NTF,ENABLE), PROVISION_DATA_MAX_LENGTH, PERM(RI, ENABLE)},
    [JMESHS_IDX_MESH_PROVISIONING_DATA_OUT_NTF_CFG] = {{ATT_DESC_CLIENT_CHAR_CFG&0xff,ATT_DESC_CLIENT_CHAR_CFG>>8}, PERM(RD, ENABLE)|PERM(WRITE_REQ,ENABLE), 0, 0},
		
    [JMESHS_IDX_MESH_NETWORK_TRANSMIT_IN_CHAR]    = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_NETWORK_TRANSMIT_IN_VAL]     = {{0x01,0x2b}, PERM(WP, NO_AUTH)|PERM(WRITE_REQ, ENABLE)|PERM(RD, ENABLE), NETWORK_TRANSMIT_LENGTH, PERM(RI, ENABLE)},
		
    [JMESHS_IDX_MESH_NETWORK_TRANSMIT_OUT_CHAR]    = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_NETWORK_TRANSMIT_OUT_VAL]     = {{0x00,0x2b}, PERM(WP, NO_AUTH)|PERM(WRITE_REQ, ENABLE)|PERM(WRITE_COMMAND,ENABLE)|PERM(RD, ENABLE)|PERM(NTF,ENABLE), NETWORK_TRANSMIT_LENGTH, PERM(RI, ENABLE)},
    [JMESHS_IDX_MESH_NETWORK_TRANSMIT_OUT_NTF_CFG] = {{ATT_DESC_CLIENT_CHAR_CFG&0xff,ATT_DESC_CLIENT_CHAR_CFG>>8}, PERM(RD, ENABLE)|PERM(WRITE_REQ,ENABLE), 0, 0},

    [JMESHS_IDX_MESH_PROXY_CONFIG_IN_CHAR]    = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_PROXY_CONFIG_IN_VAL]     = {{0x02,0x2b}, PERM(WP, NO_AUTH)|PERM(WRITE_REQ, ENABLE), PROXY_TRANSMIT_LENGTH, PERM(RI, ENABLE)},
		
    [JMESHS_IDX_MESH_PROXY_CONFIG_OUT_CHAR]    = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_PROXY_CONFIG_OUT_VAL]     = {{0x03,0x2b}, PERM(RD, ENABLE)|PERM(NTF,ENABLE), PROXY_TRANSMIT_LENGTH, PERM(RI, ENABLE)},
    [JMESHS_IDX_MESH_PROXY_CONFIG_OUT_NTF_CFG] = {{ATT_DESC_CLIENT_CHAR_CFG&0xff,ATT_DESC_CLIENT_CHAR_CFG>>8}, PERM(RD, ENABLE)|PERM(WRITE_REQ,ENABLE), 0, 0},

    [JMESHS_IDX_MESH_BEACON_IN_CHAR]    = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_BEACON_IN_VAL]     = {{0x04,0x2b}, PERM(WP, NO_AUTH)|PERM(WRITE_REQ, ENABLE), PROXY_TRANSMIT_LENGTH, PERM(RI, ENABLE)},
		
    [JMESHS_IDX_MESH_BEACON_OUT_CHAR]    = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_BEACON_OUT_VAL]     = {{0x05,0x2b}, PERM(RD, ENABLE)|PERM(NTF,ENABLE), PROXY_TRANSMIT_LENGTH, PERM(RI, ENABLE)},
    [JMESHS_IDX_MESH_BEACON_OUT_NTF_CFG] = {{ATT_DESC_CLIENT_CHAR_CFG&0xff,ATT_DESC_CLIENT_CHAR_CFG>>8}, PERM(RD, ENABLE)|PERM(WRITE_REQ,ENABLE), 0, 0},
	        
    [JMESHS_IDX_MESH_MAC_CHAR]    = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_MAC_VAL]     = {{0x06,0x2b}, PERM(WP, NO_AUTH)|PERM(WRITE_REQ, ENABLE)|PERM(RD, ENABLE)|PERM(NTF,ENABLE), PROXY_TRANSMIT_LENGTH, PERM(RI, ENABLE)},
    [JMESHS_IDX_MESH_MAC_NTF_CFG] = {{ATT_DESC_CLIENT_CHAR_CFG&0xff,ATT_DESC_CLIENT_CHAR_CFG>>8}, PERM(RD, ENABLE)|PERM(WRITE_REQ,ENABLE), 0, 0},
    
		[JMESHS_IDX_MESH_APP_TRANMISSION_DATA_IN_CHAR]    = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_APP_TRANMISSION_DATA_IN_VAL]     = {{0x07,0x2b}, PERM(WP, NO_AUTH)|PERM(WRITE_REQ, ENABLE), PROXY_TRANSMIT_LENGTH, PERM(RI, ENABLE)},
		
    [JMESHS_IDX_MESH_APP_TRANMISSION_DATA_OUT_CHAR]    = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_APP_TRANMISSION_DATA_OUT_VAL]     = {{0x08,0x2b}, PERM(RD, ENABLE)|PERM(NTF,ENABLE), PROXY_TRANSMIT_LENGTH, PERM(RI, ENABLE)},
    [JMESHS_IDX_MESH_APP_TRANMISSION_DATA_OUT_NTF_CFG] = {{ATT_DESC_CLIENT_CHAR_CFG&0xff,ATT_DESC_CLIENT_CHAR_CFG>>8}, PERM(RD, ENABLE)|PERM(WRITE_REQ,ENABLE), 0, 0},

    [JMESHS_IDX_MESH_CONFIG_CMD_CHAR]    = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_CONFIG_CMD_VAL]     = {{0x09,0x2b}, PERM(WP, NO_AUTH)|PERM(WRITE_REQ, ENABLE)|PERM(WRITE_COMMAND,ENABLE)|PERM(RD, ENABLE)|PERM(NTF,ENABLE), SERIAL_TRANSMIT_LENGTH, PERM(RI, ENABLE)},
    [JMESHS_IDX_MESH_CONFIG_CMD_NTF_CFG] = {{ATT_DESC_CLIENT_CHAR_CFG&0xff,ATT_DESC_CLIENT_CHAR_CFG>>8}, PERM(RD, ENABLE)|PERM(WRITE_REQ,ENABLE), 0, 0},
	   
		[JMESHS_IDX_MESH_TEST_CHAR]    = {{ATT_DECL_CHARACTERISTIC&0xff,ATT_DECL_CHARACTERISTIC>>8}, PERM(RD, ENABLE), 0, 0},
    [JMESHS_IDX_MESH_TEST_VAL]     = {{0x0a,0x2b}, PERM(WP, NO_AUTH)|PERM(WRITE_REQ, ENABLE)|PERM(RD, ENABLE)|PERM(NTF,ENABLE), PROXY_TRANSMIT_LENGTH, PERM(RI, ENABLE)},
    [JMESHS_IDX_MESH_TEST_NTF_CFG] = {{ATT_DESC_CLIENT_CHAR_CFG&0xff,ATT_DESC_CLIENT_CHAR_CFG>>8}, PERM(RD, ENABLE)|PERM(WRITE_REQ,ENABLE), 0, 0},
	        
};

void jmesh_add_prov_svc(void)
{
    struct gattm_add_svc_req *req = AHI_MSG_ALLOC_DYN(GATTM_ADD_SVC_REQ,TASK_ID_GATTM,\
        gattm_add_svc_req,sizeof(jmesh_prov_svc_att_db));
    struct gattm_svc_desc *svc = &req->svc_desc;
    memcpy(svc,&jmesh_prov_svc_desc,sizeof(jmesh_prov_svc_desc));
    memcpy(svc->atts,jmesh_prov_svc_att_db,sizeof(jmesh_prov_svc_att_db));
    osapp_msg_build_send(req, sizeof(struct gattm_svc_desc)+sizeof(jmesh_prov_svc_att_db));
}
