


//#include"../network/jmesh_netkey.h"
//#include"../foundation/state/jmesh_appkey.h"
//#include"../foundation/state/jmesh_TTL.h"
//#include"jmesh_device.h"
//#include"../access/jmesh_access.h"
#include"../app/expand/app_expand2/light/light_server.h"
#include"../app/expand/app_expand2/water/water.h"
#include"jmesh_config.h"
#include"jmesh_save.h"
#include "beidian_app_cfg.h"

#ifdef JMESH_SAVE_DEFINE
JMESH_SAVE_CREATE(JMESH_SAVE_FEATURES)
JMESH_SAVE_CREATE(JMESH_SAVE_ADDR)
JMESH_SAVE_CREATE(JMESH_SAVE_DEFAULT_TTL)
JMESH_SAVE_CREATE(JMESH_SAVE_IV_INDEX)
JMESH_SAVE_CREATE(JMESH_SAVE_SEQ)
JMESH_SAVE_CREATE(JMESH_SAVE_STATE_FLAGS)
JMESH_SAVE_CREATE(JMESH_SAVE_BAUTRATE)
JMESH_SAVE_CREATE(JMESH_SAVE_REALCOMM_PARA)
JMESH_SAVE_CREATE(JMESH_ADV_SCAN_TIME)
JMESH_SAVE_CREATE(JMESH_SAVE_DBM)
JMESH_SAVE_BUFFER_CREATE(JMESH_SAVE_NETKEY, JMESH_NETKEY_MAX_NUM)
JMESH_SAVE_BUFFER_CREATE(JMESH_SAVE_APPKEY, JMESH_APPKEY_MAX_NUM)
JMESH_SAVE_BUFFER_CREATE(JMESH_SAVE_DEVICE,JMESH_DEVICE_MAX_NUM)
JMESH_SAVE_BUFFER_CREATE(JMESH_SAVE_MODEL,JMESH_ELEMENT_REGISTER_MODEL_MAX_NUM)
JMESH_SAVE_BUFFER_CREATE(JMESH_SAVE_LIGHT_MODE_PARA,LIGHT_MODE_SIZE)
JMESH_SAVE_BUFFER_CREATE(JMESH_SAVE_PWM,JMESH_PWM_MAX_NUM)

JMESH_SAVE_CREATE(JMESH_SAVE_ROLE)
JMESH_SAVE_CREATE(JMESH_SAVE_LOWPOWER_PARAM)
JMESH_SAVE_CREATE(WATER_PARAM)
JMESH_SAVE_CREATE(WATER_VALUE)
JMESH_SAVE_BUFFER_CREATE(WATER_HISTORY,WATER_HISTORY_SIZE)
JMESH_SAVE_BUFFER_CREATE(WATER_RECORD,WATER_RECORD_SIZE)

JMESH_SAVE_CREATE(WATER_GATE_PARAM)

JMESH_SAVE_CREATE(JMESH_REALCOMM_SEND_SAVE)
JMESH_SAVE_CREATE(JMESH_JZQ_ADDR_SAVE)
JMESH_SAVE_CREATE(JMESH_SAVE_APP_USER_ACCOUNT)
JMESH_SAVE_CREATE(JMESH_SAVE_LAMP_MODE_INFO)

JMESH_SAVE_CREATE(JMESH_SAVE_WIRLESS_TECH)
#ifdef  KEHUA_GAS 
JMESH_SAVE_CREATE(JMESH_SAVE_REPORT_INTERVAL)
JMESH_SAVE_CREATE(JMESH_SAVE_COLLECT_INTERVAL)
#endif
#ifdef  KEHUA_WINDOW 
JMESH_SAVE_CREATE(JMESH_SAVE_REPORT_PERIOD)
JMESH_SAVE_CREATE(JMESH_SAVE_REPORT_COUNT)
#endif
#if	(defined KEHUA_TRANSFER_ARM)||(defined KEHUA_ARM_BX2400_470)
JMESH_SAVE_CREATE(JMESH_SAVE_ARM_STATE)
#endif

JMESH_SAVE_CREATE(JMESH_SAVE_LAMP_PWM)

JMESH_SAVE_CREATE(JMESH_SAVE_RESET_COUNT)
JMESH_SAVE_CREATE(JMESH_LOG_TYPE_COUNT)

#if (defined Three_Remote_Switch)||(defined Ble_Remote_Switch)
JMESH_SAVE_CREATE(JMESH_REMOTE_CONTROL_INFO)
JMESH_SAVE_CREATE(JMESH_SAVE_REMOTE_MODE_INFO)
#endif

#ifdef Scene_Panel
JMESH_SAVE_CREATE(JMESH_SCENE_PANEL_INFO)
JMESH_SAVE_CREATE(JMESH_SAVE_SCENE_MODE_INFO)
#endif
#endif // JMESH_SAVE_H

