#ifndef JMESH_CONFIG_H
#define JMESH_CONFIG_H
#include"jmesh_types.h"

/*mesh SDK version:2.5.2*/
#define MAINVER 2
#define SUBVER1 5
#define SUBVER2 2

#define JMESH_WDT_ENABLE
#define JMESH_WDT_PERIOD_MS 0xF

/*pwm channels*/
#define JMESH_PWM_MAX_NUM 5

/**< keys */
#define JMESH_NETKEY_MAX_NUM 2
#define JMESH_APPKEY_MAX_NUM 5
#define JMESH_DEVICE_MAX_NUM 1
#define JMESH_MODEL_MAX_NUM  10

#define JMESH_IV_INDEX_UPDATE_LASTING_HOUR 96
#define JMESH_IV_INDEX_UPDATE_INTERVAL_HOUR 96
#define JMESH_IV_INDEX_RECOVER_INTERVAL_HOUR 192
#define JMESH_IV_INDEX_RECOVER_GREATER_MAX   42

#define JMESH_INIT_IV_INDEX         0x12345678
#define JMESH_INVALID_IV_INDEX      0 /**< do not change this */
#define JMESH_DEFAULT_NODE_IDENTITY 0

//test
//#define JMESH_NETKEY {0x44,0x55,0x66,0x77,0xa5,0xa6,0xa7,0xa8,0x09,0x10,0x11,0x12,0x13,0x14,0x15,0x16}
//#define JMESH_APPKEY {0x44,0x55,0x66,0x77,0xa5,0xa6,0xa7,0xa8,0x09,0x10,0x11,0x12,0x13,0x14,0x15,0x16}

//xiao
#define JMESH_NETKEY {0xaa,0xbb,0xcc,0xdd,0xa5,0xa6,0xa7,0xa8,0x09,0x10,0x11,0x12,0x11,0x22,0x33,0x44}
#define JMESH_APPKEY {0xaa,0xbb,0xcc,0xdd,0xa5,0xa6,0xa7,0xa8,0x09,0x10,0x11,0x12,0x11,0x22,0x33,0x44}

//me
//#define JMESH_NETKEY {0x1e,0x2c,0x38,0x77,0xb0,0xa6,0xa7,0xa8,0x09,0x10,0x11,0x12,0x11,0x22,0x33,0x46}
//#define JMESH_APPKEY {0x1e,0x2c,0x38,0x77,0xb0,0xa6,0xa7,0xa8,0x09,0x10,0x11,0x12,0x11,0x22,0x33,0x46}

/**< features */
#define JMESH_FEATURE_DISABLE     0
#define JMESH_FEATURE_ENABLE      1
#define JMESH_FEATURE_UNSUPPORTED 2

#define JMESH_FEATURE_RELAY    JMESH_FEATURE_ENABLE
#define JMESH_FEATURE_PROXY    JMESH_FEATURE_ENABLE
#define JMESH_FEATURE_FRIEND   JMESH_FEATURE_DISABLE
#define JMESH_FEATURE_LOWPOWER JMESH_FEATURE_DISABLE
#if((JMESH_FEATURE_FRIEND==JMESH_FEATURE_ENABLE)&&(JMESH_FEATURE_LOWPOWER==JMESH_FEATURE_ENABLE))
    #error feature friend and lowpower cannot both be enable
#endif

/**< print logs */
//#define JMESH_ROUTE_PRINTABLE 1
//#define JMESH_CMD_PRINTABLE 1
//#define JMESH_INFO_PRINTABLE 1
//#define JMESH_NOTE_PRINTABLE 1
//#define JMESH_WARNING_PRINTABLE 1
//#define JMESH_ERROR_PRINTABLE 1

#define JMESH_LOG_LVL_DEBUG 5
#define JMESH_LOG_LVL_INFO 4
#define JMESH_LOG_LVL_NOTE 3
#define JMESH_LOG_LVL_WARN 2
#define JMESH_LOG_LVL_ERROR 1
#define JMESH_LOG_LVL_NONE 0

#define JMESH_LOG_LVL JMESH_LOG_LVL_INFO

#define JMESH_CMD_OUTPUT_NONE 0
#define JMESH_CMD_OUTPUT_UART 1
#define JMESH_CMD_OUTPUT_GATT 2
#define JMESH_CMD_OUTPUT_BOTH 3

#define JMESH_CMD_OUTPUT_CHOOSE JMESH_CMD_OUTPUT_BOTH

#define JMESH_CMD_INTERFACE_UART 0xff
#define JMESH_CMD_GATT_USE_PROXY 1


/**< pdu cache */
#define JMESH_BLE_MTU_SIZE 243

#define JMESH_PDU_UNSEGMENT_SIZE JMESH_BLE_MTU_SIZE/**< 243 */
#define JMESH_PDU_NETWORK_CONTROL_MIC_SIZE  JMESH_MIC64_SIZE/**< 4 */
#define JMESH_PDU_NETWORK_ACCESS_MIC_SIZE   JMESH_MIC32_SIZE/**< 8 */
#define JMESH_PDU_UPPER_ACCESS_MIC_SIZE     JMESH_MIC32_SIZE/**< 4 */

#define JMESH_LONG_PDU_CACHE_NUM 15
#define JMESH_SHORT_PDU_CACHE_NUM 20

#define JMESH_SHORT_PDU_SIZE 48
#define JMESH_LONG_PDU_SIZE 470

/**< BLE adv */
//#define JMESH_ADV_MAX_MS 90
#define JMESH_ADV_MIN_MS ((JMESH_FEATURE_ENABLE==jmesh_get_lowpower_feature())?10:10)
#define JMESH_SCAN_MAX_MS ((JMESH_FEATURE_ENABLE==jmesh_get_lowpower_feature())?100:100)
#define JMESH_SCAN_MIN_MS ((JMESH_FEATURE_ENABLE==jmesh_get_lowpower_feature())?10:10)
#define JMESH_ADV_CACHE_SIZE 29
#define JMESH_ADV_REPEAT_NUM 10

#define JMESH_CONNECT_MIN_MS 1000

/**< light */
#define LIGHT_DIRECTION 0//0-reverse
#define LIGHT_SPEED_TICKS 15
#define LIGHT_ON_TICKS 80
#define LIGHT_OFF_TICKS 160

/**< friend */
#define JMESH_FRIEND_NETKEY_INDEX 0
#define JMESH_FRIENDSHIP_MAX_NUM 30/**< a friend establish friendship num ,a low power node cache friend offer num*/
#define JMESH_FRIEND_CACHE_QUEUE_SIZE 10/**< a friendship cache pdu num */
#define JMESH_FRIEND_RECEIVE_WINDOW 100/**< 1-256 ms */

/**< 0=1,1=1.5,2=2,3=2.5 */
#define JMESH_FRIEND_FACTOR_1_0 0
#define JMESH_FRIEND_FACTOR_1_5 1
#define JMESH_FRIEND_FACTOR_2_0 2
#define JMESH_FRIEND_FACTOR_2_5 3

#define JMESH_FRIEND_RSSI_FACTOR JMESH_FRIEND_FACTOR_2_0
#define JMESH_FRIEND_RECEIVE_WINDOW_FACTOR JMESH_FRIEND_FACTOR_2_0
#define JMESH_FRIEND_MIN_QUEUE_SIZE_LOG 3/**< 2^3=8 */
#define JMESH_FRIEND_RECEIVE_DELAY 100/**<  */
#define JMESH_FRIEND_POLL_TIMEOUT  100UL/**< 9-34bbff,100*100ms=10s */
#define JMESH_FRIEND_REQUEST_INTERVAL_MS 10000/**< must be larger than 1.1s */

/**< access models */
#define JMESH_ELEMENT_REGISTER_MODEL_MAX_NUM 5
#define JMESH_MODEL_INVALID_ID 0xffff
#define JMESH_MODEL_COMPANY_ID 0xbcbd

#define JMESH_BIND_APP_MAX_NUM 6
#define JMESH_SUBSCRIPTION_LIST_SIZE 5

#define JMESH_SEQ_WARNING_FLOW 0x00efffff
#define JMESH_PRODUCT_ID  2
#define JMESH_VERSION_ID  3
#define REPLAY_PROTECTION_LIST_SIZE 100
#define JMESH_ELEMENT_LOC           0xffff

/**< beacons */
#define JMESH_ADV_TYPE_BEACON 0x2A
#define JMESH_ADV_TYPE_MESSAGE 0x2B
#define JMESH_ADV_TYPE_PROVISIONING 0x2C
#define JMESH_ADV_TYPE_OTA 0x2D

#define JMESH_BEACON_TYPE_DEVICE 0
#define JMESH_BEACON_TYPE_SECURE 1
#define JMESH_BEACON_TYPE_ROUTING 2
#define JMESH_BEACON_TYPE_CONNECT 3

#define JMESH_DEVICE_BEACON_INTERVAL_S 3
#define JMESH_DEVICE_URI "bcmeter light controller"
#define JMESH_DEVICE_URI_HASH 0x12345678

#define JMESH_SECURE_BEACON_EXPECTED_INTERVAL_S  6
#define JMESH_SECURE_BEACON_OBSERVATION_PERIOD_S 30
#define JMESH_SECURE_BEACON_MAX_INTERVAL_S       60

/**< routings */
//#define JMESH_ROUTING_TABLE_SIZE 1/**< 30*3 */
//#define JMESH_ROUTING_RECORD_SIZE 3
//#define JMESH_ROUTING_DISTANCE_LIMIT 9

#define JMESH_ROUTING_NEIGHBOR_SIZE  50
#define JMESH_ROUTING_MAINTAIN_INTERVAL_MIN_MS 9000/**< 9s */
#define JMESH_ROUTING_MAINTAIN_INTERVAL_MAX_MS 11000/**< 11s */
#define JMESH_ROUTING_NEIGHBOR_LIFETIME_S 60
#define JMESH_ROUTING_NEIGHBOR_SHARE_INTERVAL 6/**< 60s */

#define JMESH_ROUTING_DISCONNECT_TRY_INTERVAL 360/**< 360*10s=1h */
#define JMESH_ROUTING_BEACON_INTERVAL_MIN_MS 8000
#define JMESH_ROUTING_BEACON_INTERVAL_MAX_MS 15000

#define JMESH_ROUTING_FIND_DEFAULT_TTL 7
#define JMESH_ROUTING_HEARTBEAT_DEFAULT_TTL 7
#define JMESH_ROUTING_REMOVE_DEFAULT_TTL 7

#define JMESH_ROUTING_NEIGHBOR_MIN_RSSI 129/**<  */

#define JMESH_ROUTING_NEIGHBOR_CONNECT_INTERVAL_MS 1000
#define JMESH_ROUTING_NEIGHBOR_CONNECT_INTERVAL_MIN_MS 3000
#define JMESH_ROUTING_NEIGHBOR_CONNECT_INTERVAL_MAX_MS 3000

#define JMESH_GATT_LINK_IS_READY_S 6

/**< network interface */
#define JMESH_INTERFACE_INVALID 0xff

#define JMESH_FILTER_TYPE_WHITE_LIST 0
#define JMESH_FILTER_TYPE_BLACK_LIST 1
#define JMESH_FILTER_SIZE 10

#define JMESH_NETWORK_CIPHER_PDU_CACHE_SIZE 4
#define JMESH_NETWORK_CIPHER_PDU_CACHE_NUM 20

#define JMESH_NETWORK_PLAIN_PDU_CACHE_SIZE 4
#define JMESH_NETWORK_PLAIN_PDU_CACHE_NUM 20

#define JMESH_NETWORK_CIPHER_CACHE_OFFSET        2/**< first 2 obfuscated pdu octets*/
#define JMESH_NETWORK_PLAIN_CACHE_OFFSET        5/**< seq(lower 2 octets) + src */

#define JMESH_SEQ_LIST_SIZE 220

//#define JMESH_UPPER_DEFAULT_MIC_SIZE JMESH_MIC32_SIZE

/**< a full unsegment pdu  3 opcode + 8 data +4 MIC,order suggest not bigger than 8*/
#define JMESH_UPPER_UNSEGMENT_MAX_LENGTH (JMESH_LOWER_ACCESS_UNSEGMENT_PDU_SIZE-JMESH_UPPER_DEFAULT_MIC_SIZE)
#define JMESH_CONTORL_UNSEGMENT_MAX_LENGTH 11

#endif // JMESH_CONFIG_H
